apiVersion: v1
kind: Service
metadata:
  labels:
    app: server
  name: server
spec:
  type: NodePort
  ports:
    - name: "server-service"
      port: 5001
      targetPort: 8193
      nodePort: 31003
  selector:
    app: server
